name: run-all-tests
on:
  pull_request:
    branches-ignore:
      - release
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: '16.2.0'
      - run: yarn
      - name: Typecheck
        run: yarn typecheck
      - name: Unit Tests
        run: yarn test
